### ISSUE TITLE
Cleanup for v0.6

### ISSUE THREAD

**Issue by cortner** [cortner/SaddleSearch.jl#12]
## TODO

- [ ] move initial path into test set 
- [ ] merge SM and CO branches => master
- [ ] renaming
- [ ] cleanup ODE solver 
   * [ ] remove time 
   * [ ] evaluate P inside `odesolve` rather than in `f` and in `g`
   * [ ] dimer needs a different tolerance mode
   * [ ] dimer also needs a different logging and reporting scheme (`tol_trans`, `tol_rot`)
- [ ] should string type methods return the entire history without being asked to do so? (no)
- [x] remove `atol` parameter, replace with `threshold = 1.0` default

**Comment by cortner** [comment]
started cleanup for 1.10 - so this is now obsolete.
